In [1]:
import argparse, time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from dgl import DGLGraph
from dgl.data import register_data_args, load_data

In [4]:
    parser = argparse.ArgumentParser(description='GCN')
    parser.add_argument("--dataset", type=str, default="syn",
            help="dropout probability")
    parser.add_argument('--syn-type', type=str, default='RMAT',
            help='Type of the synthetic graph generator')
    parser.add_argument('--syn-nodes', type=int, default=10,
            help='Type of the synthetic graph generator')
    parser.add_argument('--syn-nfeats', type=int, default=500,
            help='Number of node features')
    parser.add_argument('--syn-nclasses', type=int, default=10,
            help='Number of output classes')
    parser.add_argument('--syn-train-ratio', type=float, default=.1,
            help='Ratio of training nodes')
    parser.add_argument('--syn-val-ratio', type=float, default=.2,
            help='Ratio of validation nodes')
    parser.add_argument('--syn-test-ratio', type=float, default=.5,
            help='Ratio of testing nodes')
    # Args for GNP generator
    parser.add_argument('--syn-gnp-n', type=int, default=1000,
            help='n in gnp random graph')
    parser.add_argument('--syn-gnp-p', type=float, default=0.0,
            help='p in gnp random graph')
    parser.add_argument('--syn-seed', type=int, default=42,
            help='random seed')
    parser.add_argument('--RMAT-dataset-path', type=str, default='/home/liangshengwen/PaRMAT/Release/out.txt',
            help='Type of the synthetic graph generator')
    args = parser.parse_args(args=[])

In [5]:
    data = load_data(args)
    features = torch.FloatTensor(data.features)
    labels = torch.LongTensor(data.labels)
    train_mask = torch.ByteTensor(data.train_mask)
    val_mask = torch.ByteTensor(data.val_mask)
    test_mask = torch.ByteTensor(data.test_mask)
    in_feats = features.shape[1]
    n_classes = data.num_labels
    n_edges = data.graph.number_of_edges()

Finished synthetic dataset generation.
  NumNodes: 10
  NumEdges: 10
  NumFeats: 500
  NumClasses: 10
  NumTrainingSamples: 1
  NumValidationSamples: 2
  NumTestSamples: 5


In [11]:
data.train_mask

array([1., 1., 1., ..., 0., 0., 0.])

In [7]:
train_mask

tensor([1, 1, 1,  ..., 0, 0, 0], dtype=torch.uint8)

In [3]:
    data = load_data(args)
    features = torch.FloatTensor(data.features)
    labels = torch.LongTensor(data.labels)
    train_mask = torch.ByteTensor(data.train_mask)
    val_mask = torch.ByteTensor(data.val_mask)
    test_mask = torch.ByteTensor(data.test_mask)
    in_feats = features.shape[1]
    n_classes = data.num_labels
    n_edges = data.graph.number_of_edges()

[ 0  0  0 ... 52 59 55]
19793
aaa


In [4]:
data.labels

array([ 0,  0,  0, ..., 52, 59, 55])