In [54]:
import argparse, time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from dgl import DGLGraph
from dgl.data import register_data_args, load_data
import scipy

In [6]:
result_bank = [list() for _ in range(2)]

In [8]:
result_bank[1]

[]

In [2]:
from dgl.data.gnn_benckmark import Coauthor

In [3]:
graph = Coauthor('cs')

aaa


In [4]:
graph.graph

In [3]:
snap.TRnd()

AttributeError: module 'snap' has no attribute 'TRnd'

In [8]:
edges = np.loadtxt("/home/liangshengwen/PaRMAT/Release/out.txt", delimiter='\t')

In [49]:
data = np.ones(10)

In [50]:
data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
src, dst = edges.transpose()

In [59]:
graph = scipy.sparse.coo_matrix((data, (src, dst)), shape=(10,10))

In [61]:
G = DGLGraph().from_scipy_sparse_matrix(graph)

In [62]:
G

In [6]:
G = DGLGraph()

In [7]:
G.add_nodes(10)

In [16]:
G.add_edges(src,dst)

In [17]:
n = 1000

In [18]:
p = (2 * np.log(n) / n)

In [19]:
seed = 42

In [20]:
import networkx as nx

In [63]:
A = nx.fast_gnp_random_graph(n,p,seed,True)

In [64]:
A

In [25]:
import scipy.sparse as sp

In [27]:
B = sp.random(n,n,p,format='coo')

In [45]:
M = B.toarray()

In [47]:
M[659][483]

0.7097928120046381

In [37]:
B.row

array([659, 725, 740, ..., 818, 862, 770], dtype=int32)

In [38]:
B.col

array([483,  54, 243, ..., 761, 206, 947], dtype=int32)

In [48]:
B.data

array([0.70979281, 0.90912293, 0.90712592, ..., 0.20819499, 0.56944959,
       0.72704131])